<footer class="page-footer font-small indigo pt-3">

  <!-- Footer Links -->
    <div class="text-center px-4 text-md-left">

        <!-- Grid row -->
        <div class="row">

        <!-- Grid column -->
        <div class="col-md-2 col-sm-12 mx-auto">

            <!-- Links -->
            <h5 class="font-weight-bold foot-title text-uppercase mt-3 mb-4">univers kabsa</h5>

            <ul class="list-unstyled">
            <li class="pb-2">
                <a href="#!" class="text-white">Programme fidelité</a>
            </li>
            <li class="pb-2">
                <a href="#!" class="text-white">S'inscrire</a>
            </li>
            <li>
                <a href="#!" class="text-white">S'abonner</a>
            </li>
            </ul>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none">

        <!-- Grid column -->
        <div class="col-md-2 col-sm-12 mx-auto">

            <!-- Links -->
            <h5 class="font-weight-bold foot-title text-uppercase mt-3 mb-4">informations</h5>

            <ul class="list-unstyled">
            <li class="pb-2">
                <a href="#!" class="text-white">Qui suis-je ?</a>
            </li>
            <li>
                <a href="#!" class="text-white">Avis clients</a>
            </li>
            </ul>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none">

        <!-- Grid column -->
        <div class="col-md-2 col-sm-12 mx-auto">

            <!-- Links -->
            <h5 class="font-weight-bold foot-title text-uppercase mt-3 mb-4">aide</h5>

            <ul class="list-unstyled">
            <li>
                <a href="#!" class="text-white">Me contacter</a>
            </li>
            </ul>

        </div>
        <div class="col-md-6 col-sm-12 mx-auto">
        </div>

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->
    <div class="px-4 pb-2">
        <i class="fab fa-facebook-square mr-2"></i>
        <i class="fab fa-instagram mr-2"></i>
        <i class="fas fa-envelope"></i>
    </div>
    <!-- Copyright -->
    <div class="footer-copyright text-uppercase py-3 px-4">
        Copyright © kabsa.fr
    </div>
  <!-- Copyright -->

</footer>

